EntityBundle\Entity\Blog:
    type: entity
    table: null
    repositoryClass: EntityBundle\Repository\BlogRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titulo:
            type: string
            length: 255
        texto:
            type: text
        fecha:
            type: datetime
            
        imagen:
            type: string
            length: 255
            nullable: true
            
    
    lifecycleCallbacks: {  }
