EntityBundle\Entity\Imagenes:
    type: entity
    table: imagenes
    repositoryClass: EntityBundle\Repository\ImagenesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: string
            length: 255
            
    manyToOne:
        portfolio:
            targetEntity: Portfolio
            inversedBy: imagenes
            joinColumn:
                name: id_portfolio
                referencedColumnName: id
                
       
        
    lifecycleCallbacks: {  }
