home:
    path: /
    defaults: { _controller: AppBundle:Home:index }
aviso:
    path: /aviso
    defaults: { _controller: AppBundle:Home:aviso }
politica:
    path: /politica
    defaults: { _controller: AppBundle:Home:politica }
cookies:
    path: /cookies
    defaults: { _controller: AppBundle:Home:cookies }

    
    

    
