<?php

namespace EntityBundle\Repository;

/**
 * BlogImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogImagenRepository extends \Doctrine\ORM\EntityRepository
{
}
