<?php

namespace EntityBundle\Repository;

/**
 * EjercicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EjercicioRepository extends \Doctrine\ORM\EntityRepository
{
}
